### ISSUE TITLE
pruning leaves "unreachable" eclasses

### ISSUE THREAD

**Issue by mwillsey** [mwillsey/egg#3]
After pruning, the egraph may not be connected.

We should be able to "garbage collect" unreachable eclasses given a set of eclass roots.

**Comment by remysucre** [comment]
I have some code on my fork for this. While it does seem to cut down # of classes & nodes dramatically (from a few thousands to under 100), the code still runs very slow. It could be because I didn't touch the union-find copy, or just something stupid. I'll debug more but feel free to poke around (you want the "matrix" branch). 

https://github.com/remysucre/egg/blob/0c94dfd6c32a1aacf466b02deefac0cfa0528f5e/src/egraph.rs#L284

**Comment by remysucre** [comment]
Ha, I was walking the graph in a way that visits all possible expressions, where there's an exponential number of.

**Comment by mwillsey** [comment]
I think this is probably okay, deleting things from the union find seems painful.
